function spring_axial_fatigue_final()
    %% 输入参数
    prompt = {
        '线径 d (mm):', ...
        '弹簧外径 D_o (mm):', ...
        '弹簧内径 D_i (mm):', ...
        '有效圈数 N_a:', ...
        '抗拉强度 σ_b (MPa):', ...
        '剪切模量 G (GPa):', ...
        '材料密度 ρ (kg/m³):', ...
        '正应力疲劳安全系数 SF_σ_f:', ...
        '剪应力疲劳安全系数 SF_τ_f:', ...
        '正应力屈服安全系数 SF_σ_y:', ...
        '剪应力屈服安全系数 SF_τ_y:', ...
        '阻尼比 ζ（如 0.02）:'
    };
    def = {'1.5','16.5','13.5','100','450','80','7850','1.5','1.5','1.2','1.2','0.02'};
    answ = inputdlg(prompt, '螺旋拉伸弹簧参数输入', [1 55], def);
    if isempty(answ), return; end

    %% 单位换算
    d = str2double(answ{1}) / 1000;
    Do = str2double(answ{2}) / 1000;
    Di = str2double(answ{3}) / 1000;
    Na = str2double(answ{4});
    sigma_b = str2double(answ{5}) * 1e6;
    G = str2double(answ{6}) * 1e9;
    rho = str2double(answ{7});
    SF_sigma_f = str2double(answ{8});
    SF_tau_f = str2double(answ{9});
    SF_sigma_y = str2double(answ{10});
    SF_tau_y = str2double(answ{11});
    zeta = str2double(answ{12});
    g = 9.81;

    %% 几何与修正系数
    Dm = (Do + Di) / 2;           % 中径
    C = Dm / d;                   % 卷绕比
    Kw = (4*C - 1)/(4*C - 4) + 0.615/C;  % Wahl 修正系数

    %% 材料极限
    sigma_e = 0.5 * sigma_b;      % 正应力疲劳极限
    tau_e = 0.29 * sigma_b;       % 剪应力疲劳极限
    tau_b = 0.577 * sigma_b;      % 剪切屈服极限（von Mises）

    %% 疲劳控制载荷
    F_sigma_f = (pi * d^2 / 4) * (sigma_e / SF_sigma_f);
    F_tau_f = (pi * d^3 / (8 * Dm * Kw)) * (tau_e / SF_tau_f);
    F_fatigue = min(F_sigma_f, F_tau_f);

    %% 屈服控制载荷
    F_sigma_y = (pi * d^2 / 4) * (sigma_b / SF_sigma_y);
    F_tau_y = (pi * d^3 / (8 * Dm * Kw)) * (tau_b / SF_tau_y);
    F_yield = min(F_sigma_y, F_tau_y);

    %% 推荐极限载荷（基于屈服）
    F_total = F_yield;

    %% 动态特性
    A = pi * (d/2)^2;
    L = Na * pi * Dm;
    V = A * L;
    m = V * rho;
    k = G * d^4 / (8 * Dm^3 * Na);
    fn = (1 / (2*pi)) * sqrt(k / m);
    c = 2 * zeta * sqrt(k * m);

    %% 输出结果
    result = sprintf([...
        '弹簧参数计算结果\n\n',...
        '--- 弹簧性能参数 ---\n',...
        '刚度 k                         = %8.2f N/m\n',...
        '质量 m                         = %8.4f kg\n',...
        '固有频率 f₁                    = %8.2f Hz\n',...
        '阻尼系数 c                     = %8.4f Ns/m\n\n',...
        '--- 疲劳载荷控制 ---\n',...
        '正应力疲劳极限载荷             = %8.2f N\n',...
        '剪应力疲劳极限载荷             = %8.2f N\n',...
        '疲劳控制推荐最大载荷           = %8.2f N\n',...
        '对应最大挂载质量（疲劳）       = %8.2f kg\n\n',...
        '--- 屈服载荷控制 ---\n',...
        '正应力屈服极限载荷             = %8.2f N\n',...
        '剪应力屈服极限载荷             = %8.2f N\n',...
        '屈服控制推荐最大载荷           = %8.2f N\n',...
        '对应最大挂载质量（屈服）       = %8.2f kg\n'],...
        k, m, fn, c,...
        F_sigma_f, F_tau_f, F_fatigue, F_fatigue/g,...
        F_sigma_y, F_tau_y, F_yield, F_yield/g);

    %% 弹窗显示
    msgbox(result, '参数计算结果');
end
