% Compute fatigue & yield load limits for axial tension spring

% === Input parameters ===
prompt = {
    'Wire diameter d (mm):', ...
    'Outer diameter D_o (mm):', ...
    'Inner diameter D_i (mm):', ...
    'Active coils N_a:', ...
    'Tensile strength σ_b (MPa):', ...
    'Shear modulus G (GPa):', ...
    'Density ρ (kg/m³):', ...
    'Fatigue SF (normal stress):', ...
    'Fatigue SF (shear stress):', ...
    'Yield SF (normal stress):', ...
    'Yield SF (shear stress):', ...
    'Damping ratio ζ (e.g. 0.02):'
};
def = {'1.5','16.5','13.5','100','450','80','7850','1.5','1.5','1.2','1.2','0.02'};
options.Resize = 'on';
answ = inputdlg(prompt, 'Spring Parameters Input', [1 55], def, options);
if isempty(answ), return; end

% === Convert units ===
d = str2double(answ{1}) / 1000;
Do = str2double(answ{2}) / 1000;
Di = str2double(answ{3}) / 1000;
Na = str2double(answ{4});
sigma_b = str2double(answ{5}) * 1e6;
G = str2double(answ{6}) * 1e9;
rho = str2double(answ{7});
SF_sigma_f = str2double(answ{8});
SF_tau_f = str2double(answ{9});
SF_sigma_y = str2double(answ{10});
SF_tau_y = str2double(answ{11});
zeta = str2double(answ{12});
g = 9.81;

% === Geometry & correction factor ===
Dm = (Do + Di) / 2;
C = Dm / d;
Kw = (4*C - 1)/(4*C - 4) + 0.615/C;

% === Material limits ===
sigma_e = 0.5 * sigma_b;
tau_e = 0.29 * sigma_b;
tau_b = 0.577 * sigma_b;

% === Fatigue-limited force ===
F_sigma_f = (pi * d^2 / 4) * (sigma_e / SF_sigma_f);
F_tau_f = (pi * d^3 / (8 * Dm * Kw)) * (tau_e / SF_tau_f);
F_fatigue = min(F_sigma_f, F_tau_f);

% === Yield-limited force ===
F_sigma_y = (pi * d^2 / 4) * (sigma_b / SF_sigma_y);
F_tau_y = (pi * d^3 / (8 * Dm * Kw)) * (tau_b / SF_tau_y);
F_yield = min(F_sigma_y, F_tau_y);

% === Dynamic properties ===
A = pi * (d/2)^2;
L = Na * pi * Dm;
V = A * L;
m = V * rho;
k = G * d^4 / (8 * Dm^3 * Na);
fn = (1 / (2*pi)) * sqrt(k / m);
c = 2 * zeta * sqrt(k * m);

% === Results text ===
result = sprintf([...
    'Spring Analysis Results\n\n',...
    '--- Basic Properties ---\n',...
    'Stiffness k                     = %8.2f N/m\n',...
    'Mass m                          = %8.4f kg\n',...
    'Natural frequency f₁            = %8.2f Hz\n',...
    'Damping coefficient c           = %8.4f Ns/m\n\n',...
    '--- Fatigue Load Limit ---\n',...
    'Normal stress fatigue limit     = %8.2f N\n',...
    'Shear stress fatigue limit      = %8.2f N\n',...
    'Recommended fatigue max load    = %8.2f N\n',...
    'Max hanging mass (fatigue)      = %8.2f kg\n\n',...
    '--- Yield Load Limit ---\n',...
    'Normal stress yield limit       = %8.2f N\n',...
    'Shear stress yield limit        = %8.2f N\n',...
    'Recommended yield max load      = %8.2f N\n',...
    'Max hanging mass (yield)        = %8.2f kg\n'],...
    k, m, fn, c,...
    F_sigma_f, F_tau_f, F_fatigue, F_fatigue/g,...
    F_sigma_y, F_tau_y, F_yield, F_yield/g);

% === Display result in resizable dialog ===
h = msgbox(result, 'Spring Calculation Result', 'none');
set(h, 'Resize', 'on');  % make it resizable