# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 576)
        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 58, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(80, 10, 321, 30))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setUnderline(False)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setEnabled(True)
        self.MplWidget.setGeometry(QtCore.QRect(10, 89, 521, 431))
        self.MplWidget.setMouseTracking(True)
        self.MplWidget.setTabletTracking(True)
        self.MplWidget.setObjectName("MplWidget")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(136, 530, 800, 30))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(410, 10, 338, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.commandLinkButton_former = QtWidgets.QCommandLinkButton(self.layoutWidget)
        self.commandLinkButton_former.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.commandLinkButton_former.setFont(font)
        self.commandLinkButton_former.setObjectName("commandLinkButton_former")
        self.gridLayout.addWidget(self.commandLinkButton_former, 0, 0, 1, 1)
        self.commandLinkButton_next = QtWidgets.QCommandLinkButton(self.layoutWidget)
        self.commandLinkButton_next.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.commandLinkButton_next.setFont(font)
        self.commandLinkButton_next.setObjectName("commandLinkButton_next")
        self.gridLayout.addWidget(self.commandLinkButton_next, 0, 1, 1, 1)
        self.MplWidget_2 = MplWidget(self.centralwidget)
        self.MplWidget_2.setEnabled(True)
        self.MplWidget_2.setGeometry(QtCore.QRect(540, 90, 521, 431))
        self.MplWidget_2.setMouseTracking(True)
        self.MplWidget_2.setTabletTracking(True)
        self.MplWidget_2.setObjectName("MplWidget_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(450, 50, 331, 32))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_next = QtWidgets.QPushButton(self.widget)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout.addWidget(self.pushButton_next)
        self.pushButton_yes = QtWidgets.QPushButton(self.widget)
        self.pushButton_yes.setCheckable(False)
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.horizontalLayout.addWidget(self.pushButton_yes)
        self.pushButton_get_benchmark = QtWidgets.QPushButton(self.widget)
        self.pushButton_get_benchmark.setCheckable(False)
        self.pushButton_get_benchmark.setObjectName("pushButton_get_benchmark")
        self.horizontalLayout.addWidget(self.pushButton_get_benchmark)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "status:"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">pick the signal pulses to calculate template</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "Copyright © University of Science and Technology of China"))
        self.commandLinkButton_former.setText(_translate("MainWindow", "Former"))
        self.commandLinkButton_next.setText(_translate("MainWindow", "Next"))
        self.pushButton_next.setText(_translate("MainWindow", "NEXT"))
        self.pushButton_yes.setText(_translate("MainWindow", "YES"))
        self.pushButton_get_benchmark.setText(_translate("MainWindow", "Search signal template"))
from mplwidget_lay2 import MplWidget
